version: '3.8'
services:
  frontend:
    container_name: job-finder-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.local
    restart: always
    depends_on:
      - backend
  
  backend:
    container_name: job-finder-backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db    

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
