FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
apt-get upgrade -y && \
apt-get install -y gcc musl-dev libffi-dev libpq-dev

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]